/* Generated by Yosys 0.59+134 (git sha1 34fa8a4ff, clang++ 18.1.8 -fPIC -O3) */

module comparator_3bit(A, B, A_greater, A_equal, A_less);
  input [2:0] A;
  wire [2:0] A;
  input [2:0] B;
  wire [2:0] B;
  output [1:0] A_greater;
  wire [1:0] A_greater;
  output [1:0] A_equal;
  wire [1:0] A_equal;
  output [1:0] A_less;
  wire [1:0] A_less;
  reg A_equal_reg_0_;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  always @*
    if (_12_) A_equal_reg_0_ = _00_[0];
  INV_X1 _13_ (
    .A(A[0]),
    .ZN(_01_)
  );
  INV_X1 _14_ (
    .A(B[0]),
    .ZN(_02_)
  );
  INV_X1 _15_ (
    .A(A[1]),
    .ZN(_03_)
  );
  INV_X1 _16_ (
    .A(B[1]),
    .ZN(_04_)
  );
  INV_X1 _17_ (
    .A(A[2]),
    .ZN(_05_)
  );
  INV_X1 _18_ (
    .A(B[2]),
    .ZN(_06_)
  );
  AOI22_X1 _19_ (
    .A1(A[1]),
    .A2(_04_),
    .B1(A[2]),
    .B2(_06_),
    .ZN(_07_)
  );
  AOI22_X1 _20_ (
    .A1(A[0]),
    .A2(_02_),
    .B1(_05_),
    .B2(B[2]),
    .ZN(_08_)
  );
  AOI22_X1 _21_ (
    .A1(_01_),
    .A2(B[0]),
    .B1(_03_),
    .B2(B[1]),
    .ZN(_09_)
  );
  OAI22_X1 _22_ (
    .A1(A[0]),
    .A2(_02_),
    .B1(A[1]),
    .B2(_04_),
    .ZN(_10_)
  );
  OAI21_X1 _23_ (
    .A(_07_),
    .B1(_08_),
    .B2(_10_),
    .ZN(_11_)
  );
  AND3_X1 _24_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_09_),
    .ZN(_00_[0])
  );
  AOI221_X1 _25_ (
    .A(_00_[0]),
    .B1(_10_),
    .B2(_07_),
    .C1(_05_),
    .C2(B[2]),
    .ZN(A_greater[0])
  );
  OAI21_X1 _26_ (
    .A(_11_),
    .B1(_06_),
    .B2(A[2]),
    .ZN(_12_)
  );
  assign A_equal = { 1'b0, A_equal_reg_0_ };
  assign A_greater[1] = 1'b0;
  assign A_less = 2'b01;
  assign _00_[1] = 1'b0;
endmodule
