/* Generated by Yosys 0.59+134 (git sha1 34fa8a4ff, clang++ 18.1.8 -fPIC -O3) */

module comparator_3bit(A, B, A_greater, A_equal, A_less);
  input [2:0] A;
  wire [2:0] A;
  input [2:0] B;
  wire [2:0] B;
  output A_greater;
  wire A_greater;
  output A_equal;
  wire A_equal;
  output A_less;
  wire A_less;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  INV_X1 _10_ (
    .A(A[0]),
    .ZN(_00_)
  );
  INV_X1 _11_ (
    .A(A[1]),
    .ZN(_01_)
  );
  INV_X1 _12_ (
    .A(A[2]),
    .ZN(_02_)
  );
  INV_X1 _13_ (
    .A(B[0]),
    .ZN(_03_)
  );
  INV_X1 _14_ (
    .A(B[2]),
    .ZN(_04_)
  );
  NAND2_X1 _15_ (
    .A1(_02_),
    .A2(B[2]),
    .ZN(_05_)
  );
  XOR2_X1 _16_ (
    .A(A[1]),
    .B(B[1]),
    .Z(_06_)
  );
  AOI21_X1 _17_ (
    .A(_06_),
    .B1(B[0]),
    .B2(_00_),
    .ZN(_07_)
  );
  OAI22_X1 _18_ (
    .A1(_01_),
    .A2(B[1]),
    .B1(B[2]),
    .B2(_02_),
    .ZN(_08_)
  );
  OAI21_X1 _19_ (
    .A(_05_),
    .B1(_07_),
    .B2(_08_),
    .ZN(A_less)
  );
  AOI22_X1 _20_ (
    .A1(A[0]),
    .A2(_03_),
    .B1(_04_),
    .B2(A[2]),
    .ZN(_09_)
  );
  AND3_X1 _21_ (
    .A1(_05_),
    .A2(_07_),
    .A3(_09_),
    .ZN(A_equal)
  );
  NOR2_X1 _22_ (
    .A1(A_less),
    .A2(A_equal),
    .ZN(A_greater)
  );
endmodule
